server:
  port: 8081
spring:
  application:
    name: user-authorizer
  datasource:
    username: socialmedia
    password: socialpassword
    url: jdbc:postgresql://localhost:5433/socialmedia
  jpa:
    hibernate:
      ddl-auto: update # clear database each time
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true